In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("disaster_data.csv")
df.head()

/Users/mikalshrestha/opt/anaconda3/envs/tf/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3417: DtypeWarning: Columns (0,3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,S.No.,District,VDC/Municipality,Ward No.,Incident Place,Incident Date,Incident,Death Male,Death Female,Death Unknown,...,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44
0,1,Nawalparasi,Pratappur,5,NaN,0000-00-00,Flood,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Humla,Namkha Rural Municipality,1,NaN,0000-00-00,Heavy Rainfall,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Lalitpur,Others,NaN,Kunjeshum-2,0000-00-00,Fire,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Mahottari,Aurahi,"3,4",NaN,0000-00-00,Flood,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Morang,Itahari,NaN,NaN,0000-00-00,Fire,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.drop(df.columns[[27,28,29,30, 31, 32,33,34,35,36,37,38,39,40,41,42,43, 44]], axis=1, inplace=True)

In [4]:
df

,S.No.,District,VDC/Municipality,Ward No.,Incident Place,Incident Date,Incident,Death Male,Death Female,Death Unknown,...,Private House Fully Damaged,Private House Partially Damaged,Displaced Male(N/A),Displaced Female(N/A),Property Loss,No. of Displaced Family,Cattles Loss,Displaced Shed,Source,Remarks
0,1,Nawalparasi,Pratappur,5,NaN,0000-00-00,Flood,0,0,0,...,9,0,0,0,0.0,0,0,0,Nepal Police,NaN
1,2,Humla,Namkha Rural Municipality,1,NaN,0000-00-00,Heavy Rainfall,0,0,0,...,2,0,0,0,0.0,0,0,0,"DAO, Humla",Chhomu Lama
2,3,Lalitpur,Others,NaN,Kunjeshum-2,0000-00-00,Fire,0,0,0,...,1,0,0,0,0.0,0,0,0,Nepal Police,Kalpana Banfara
3,4,Mahottari,Aurahi,"3,4",NaN,0000-00-00,Flood,0,0,0,...,2,0,0,0,0.0,0,0,0,"DAO, Mahottari",NaN
4,5,Morang,Itahari,NaN,NaN,0000-00-00,Fire,0,0,0,...,0,0,0,0,NaN,0,0,0,Nepal Police,Masine Damai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30624,30625,Panchthar,Phalelung Rural Municipality,2.0,Khola choke,8/7/2022,Heavy Rainfall,0,0,0,...,0,1,0,0,0.0,0,0,0,Nepal Police,Dil Bahadur Guragain
30625,30626,Panchthar,Yangwarak Rural Municipality,3.0,Basantadada,8/7/2022,Landslide,0,0,0,...,0,1,0,0,0.0,0,0,0,Nepal Police,Bir Bdr Nugo
30626,30627,Dang,Tulsipur Submetropolitan City,9.0,NaN,8/8/2022,Fire,0,0,0,...,0,0,0,0,0.0,0,0,0,Nepal Police,Busma
30627,30628,Kathmandu,Budhanilkantha Municipality,10.0,Kapan,8/8/2022,Fire,0,0,0,...,0,0,0,0,0.0,0,0,0,Nepal Police,Mosa
30628,Total,NaN,NaN,NaN,NaN,NaN,NaN,5725,6332,34,...,809679,356196,260010,0,0.0,2,28094,7566,NaN,NaN

In [5]:
df.drop(df.columns[[26]], axis=1, inplace=True)

In [6]:
df.rename(columns={'VDC/Municipality': 'VDC_Municipality', 'Ward No.': 'Ward_Num', 
                  'Incident Place': 'Incident_Place','Incident Date': 'Incident_Date', 
                   'Death Male': 'Death_Male'}, inplace=True)

In [7]:
df.rename(columns={'Ward_NUM': 'Ward_Num'}, inplace=True)

In [8]:
df.rename(columns={'Death Female': 'Death_Female','Cattles Loss': 'Cattles_Loss',
                  'Property Loss': 'Property_Loss', 
                   'No. of Displaced Family': 'Num_Displaced_Family',
                   'Displaced Shed': 'Displaced_Shed'}, inplace=True)

In [9]:
df.drop('Death Unknown', axis=1, inplace=True)

In [10]:
df.rename(columns={'Total Death': 'Total_Death', 'Missing People': 'Missing_People',
                  'Affected Family': 'Affected_Family',
                  'Estimated Loss': 'Estimated_Loss', 
                   'Govt. Houses Fully Damaged': 'Govt_Houses_Fully_Damaged',
                  'Govt. Houses Partially Damaged': 'Govt_Houses_Partially_Damaged',
                   'Private House Fully Damaged': 'Private_House_Fully_Damaged',
                  'Private House Partially Damaged': 'Private_House_Partially_Damaged',
                   'Private House Partially Damaged': 'Private_House_Partially_Damaged'}, inplace=True)

In [11]:
df.drop('Displaced Male(N/A)', axis=1, inplace=True)

In [12]:
df.drop('Displaced Female(N/A)', axis=1, inplace=True)

In [13]:
df

,S.No.,District,VDC_Municipality,Ward_Num,Incident_Place,Incident_Date,Incident,Death_Male,Death_Female,Total_Death,...,Injured,Govt_Houses_Fully_Damaged,Govt_Houses_Partially_Damaged,Private_House_Fully_Damaged,Private_House_Partially_Damaged,Property_Loss,Num_Displaced_Family,Cattles_Loss,Displaced_Shed,Source
0,1,Nawalparasi,Pratappur,5,NaN,0000-00-00,Flood,0,0,0,...,0,0,0,9,0,0.0,0,0,0,Nepal Police
1,2,Humla,Namkha Rural Municipality,1,NaN,0000-00-00,Heavy Rainfall,0,0,0,...,0,0,0,2,0,0.0,0,0,0,"DAO, Humla"
2,3,Lalitpur,Others,NaN,Kunjeshum-2,0000-00-00,Fire,0,0,0,...,0,0,0,1,0,0.0,0,0,0,Nepal Police
3,4,Mahottari,Aurahi,"3,4",NaN,0000-00-00,Flood,0,0,0,...,0,0,0,2,0,0.0,0,0,0,"DAO, Mahottari"
4,5,Morang,Itahari,NaN,NaN,0000-00-00,Fire,0,0,0,...,0,0,0,0,0,NaN,0,0,0,Nepal Police
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30624,30625,Panchthar,Phalelung Rural Municipality,2.0,Khola choke,8/7/2022,Heavy Rainfall,0,0,0,...,0,0,0,0,1,0.0,0,0,0,Nepal Police
30625,30626,Panchthar,Yangwarak Rural Municipality,3.0,Basantadada,8/7/2022,Landslide,0,0,0,...,0,0,0,0,1,0.0,0,0,0,Nepal Police
30626,30627,Dang,Tulsipur Submetropolitan City,9.0,NaN,8/8/2022,Fire,0,0,0,...,0,0,0,0,0,0.0,0,0,0,Nepal Police
30627,30628,Kathmandu,Budhanilkantha Municipality,10.0,Kapan,8/8/2022,Fire,0,0,0,...,0,0,0,0,0,0.0,0,0,0,Nepal Police
30628,Total,NaN,NaN,NaN,NaN,NaN,NaN,5725,6332,14365,...,34969,2704,3810,809679,356196,0.0,2,28094,7566,NaN

In [14]:
df = df.drop(30628)

In [15]:
df

,S.No.,District,VDC_Municipality,Ward_Num,Incident_Place,Incident_Date,Incident,Death_Male,Death_Female,Total_Death,...,Injured,Govt_Houses_Fully_Damaged,Govt_Houses_Partially_Damaged,Private_House_Fully_Damaged,Private_House_Partially_Damaged,Property_Loss,Num_Displaced_Family,Cattles_Loss,Displaced_Shed,Source
0,1,Nawalparasi,Pratappur,5,NaN,0000-00-00,Flood,0,0,0,...,0,0,0,9,0,0.0,0,0,0,Nepal Police
1,2,Humla,Namkha Rural Municipality,1,NaN,0000-00-00,Heavy Rainfall,0,0,0,...,0,0,0,2,0,0.0,0,0,0,"DAO, Humla"
2,3,Lalitpur,Others,NaN,Kunjeshum-2,0000-00-00,Fire,0,0,0,...,0,0,0,1,0,0.0,0,0,0,Nepal Police
3,4,Mahottari,Aurahi,"3,4",NaN,0000-00-00,Flood,0,0,0,...,0,0,0,2,0,0.0,0,0,0,"DAO, Mahottari"
4,5,Morang,Itahari,NaN,NaN,0000-00-00,Fire,0,0,0,...,0,0,0,0,0,NaN,0,0,0,Nepal Police
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30623,30624,Jhapa,Kankai Municipality,3.0,Jcb Bhawan,8/7/2022,Fire,0,0,0,...,3,0,0,0,1,0.0,0,0,0,Nepal Police
30624,30625,Panchthar,Phalelung Rural Municipality,2.0,Khola choke,8/7/2022,Heavy Rainfall,0,0,0,...,0,0,0,0,1,0.0,0,0,0,Nepal Police
30625,30626,Panchthar,Yangwarak Rural Municipality,3.0,Basantadada,8/7/2022,Landslide,0,0,0,...,0,0,0,0,1,0.0,0,0,0,Nepal Police
30626,30627,Dang,Tulsipur Submetropolitan City,9.0,NaN,8/8/2022,Fire,0,0,0,...,0,0,0,0,0,0.0,0,0,0,Nepal Police
30627,30628,Kathmandu,Budhanilkantha Municipality,10.0,Kapan,8/8/2022,Fire,0,0,0,...,0,0,0,0,0,0.0,0,0,0,Nepal Police

In [16]:
nan_cols = [i for i in df.columns if df[i].isnull().any()]
nan_cols

['District',
 'Ward_Num',
 'Incident_Place',
 'Estimated_Loss',
 'Property_Loss',
 'Source']

In [17]:
df['Source'] = df['Source'].fillna("Nepal Police")

In [18]:
df['District'] = df['District'].fillna("Jhapa")

In [19]:
df['District'].isna().sum()

0

In [20]:
df['Incident_Place'] = df.apply(lambda row: row['VDC_Municipality'] if pd.isnull(row['Incident_Place']) else row['Incident_Place'], axis=1)

In [21]:
df['Estimated_Loss'] = df['Estimated_Loss'].fillna(df['Estimated_Loss'].value_counts().idxmax())

In [22]:
df['Property_Loss'] = df['Property_Loss'].fillna(df['Property_Loss'].value_counts().idxmax())

In [23]:
nan_cols = [i for i in df.columns if df[i].isnull().any()]
nan_cols

['Ward_Num']

In [24]:
df = df.ffill()

In [25]:
nan_cols = [i for i in df.columns if df[i].isnull().any()]
nan_cols

[]

In [26]:
df.describe()

,Death_Male,Death_Female,Total_Death,Missing_People,Affected_Family,Estimated_Loss,Injured,Govt_Houses_Fully_Damaged,Govt_Houses_Partially_Damaged,Private_House_Fully_Damaged,Private_House_Partially_Damaged,Property_Loss,Num_Displaced_Family,Cattles_Loss,Displaced_Shed
count,30628.000000,30628.000000,30628.000000,30628.000000,30628.000000,3.062800e+04,30628.000000,30628.000000,30628.000000,30628.000000,30628.000000,30628.0,30628.000000,30628.000000,30628.000000
mean,0.186920,0.206739,0.469015,0.039441,4.362577,1.464913e+06,1.141733,0.088285,0.124396,26.435908,11.629751,0.0,0.000065,0.917265,0.247029
std,10.145706,13.397596,23.516559,1.254272,135.358054,6.282675e+07,53.684656,5.521178,5.389623,1243.510740,446.762845,0.0,0.008081,27.261462,2.119900
min,0.000000,0.000000,0.000000,0.000000,-2.000000,0.000000e+00,-2.000000,-1.000000,-1.000000,-3.000000,0.000000,0.0,0.000000,-2.000000,-2.000000
25%,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,1.000000,3.500000e+05,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,0.000000
max,1507.000000,2063.000000,3570.000000,139.000000,17376.000000,1.005285e+10,7950.000000,710.000000,684.000000,89884.000000,55131.000000,0.0,1.000000,2000.000000,181.000000

In [27]:
#df.to_excel("disaster_data_result.xlsx")

In [28]:
df.to_csv('disaster_data_result.csv')

In [29]:
# from pymongo import MongoClient

# # Connect to MongoDB
# client = MongoClient('localhost', 27017)
# db = client['disaster']
# collection = db['incident']
# df.reset_index(drop= True, inplace=True)
# data_dict = df.to_dict("records")
# # Insert collection
# collection.insert_many(data_dict)